on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n my1azurecontainerregistry -g my1azurecontainerregistry88e4-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n my1azurecontainerregistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n my1azurecontainerregistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n my1azurecontainerregistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: my1azurecontainerregistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/docker" -f  "docker/Dockerfile" -t my1azurecontainerregistry.azurecr.io/clusteraks01:${{ github.sha }}
        docker push my1azurecontainerregistry.azurecr.io/clusteraks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_clusteraks01_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clusteraks01faa8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clusteraks01faa8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clusteraks01faa8
        container-registry-url: my1azurecontainerregistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: clusteraks01dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: clusteraks01faa8
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          my1azurecontainerregistry.azurecr.io/clusteraks01:${{ github.sha }}
        imagepullsecrets: |
          clusteraks01dockerauth